import type {Metadata} from 'next';
import Image from 'next/image';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import FAQ from '@/components/FAQ';
import Icon from '@/components/Icon';
import {gurus,site} from '@/lib/site';
export const metadata:Metadata={alternates:{canonical:'/'}};
const faq=[
 {question:'Mikä Älypuhelin on?',answer:'Älypuhelin on tekoälypuhelinpalvelu. Soitat tavallisella puhelimella, kerrot asiasi ja keskustelet tekoälyn kanssa. Tältä sivulta löydät myös eri aiheisiin keskittyvät Guru-palvelumme.'},
 {question:'Tarvitsenko sovelluksen tai käyttäjätilin?',answer:'Et tarvitse kumpaakaan. Puhelinpalveluun riittää tavallinen puhelu. Jos liittymässäsi on maksullisten palvelunumeroiden esto, soittaminen ei onnistu ennen eston muuttamista operaattorillasi.'},
 {question:'Mitä soittaminen maksaa?',answer:'Älypuhelimen numerossa 0600 411 104 palvelumaksu on 0,98 euroa minuutilta. Lisäksi operaattorisi veloittaa paikallisverkko- tai matkapuhelinmaksun. Esimerkiksi viiden minuutin palvelumaksu on 4,90 euroa. Kuukausimaksua tai jatkuvaa tilausta ei ole.'},
 {question:'Voinko soittaa myös illalla tai viikonloppuna?',answer:'Kyllä. Älypuhelin palvelee ympäri vuorokauden. Voit soittaa silloin, kun sinulle sopii.'},
 {question:'Voiko tekoälyn vastauksiin aina luottaa?',answer:'Tekoäly voi erehtyä. Käytä vastauksia apuna asioiden ymmärtämiseen ja tarkista tärkeät tiedot luotettavasta lähteestä. Palvelu ei korvaa lääkäriä, eläinlääkäriä tai muuta tilanteeseesi perehtynyttä ammattilaista.'},
 {question:'Kuka palvelun tuottaa?',answer:'Älypuhelimen tuottaa suomalainen Valkomedia Oy, Y-tunnus 2360847-3. Palvelua koskevissa asioissa tavoitat meidät osoitteesta visa.valkonen@kaupallinen.fi. Tietojen käsittelystä kerromme tietosuojaselosteessa.'},
];
export default function Home(){return <><Navigation/><main id="main">
 <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/>Tekoäly puhelimen päässä · 24/7</div><h1>Mistä haluaisit<br/><span className="word-mark">puhua<svg viewBox="0 0 320 20" preserveAspectRatio="none" aria-hidden="true"><path d="M4 15Q130 0 314 10"/></svg></span>?</h1><p className="hero-lead">Pieni pulma vai isompi kysymys?<br/>Löydä sopiva Guru tai juttele tekoälyn kanssa. Ihan tavallisella puhelulla.</p><div className="hero-actions"><a href="#gurut" className="button">Löydä oma Guru<Icon name="arrow"/></a><a href="#miten-toimii" className="text-link">Näin se toimii<span aria-hidden="true">↓</span></a></div><div className="hero-proof"><span><Icon name="check"/>Ei sovellusta</span><span><Icon name="check"/>Ei kirjautumista</span></div></div><div className="hero-art"><div className="art-caption"><Icon name="sound"/><span>Hyvä puhelu alkaa<br/><strong>kuuntelusta.</strong></span></div><Image src="/brand/kaiku.png" width={1254} height={1254} alt="Kaiku, Älypuhelimen suurikorvainen maskotti, kuuntelee käsi korvalla." priority sizes="(max-width: 700px) 90vw, 50vw" className="kaiku-hero"/><div className="kaiku-note"><span className="note-dot"/>Kaiku kuulolla.</div><span className="art-orbit" aria-hidden="true"/></div></section>
 <div className="intro-strip"><div className="container"><span>Arjen kysymyksiä varten.</span><p>Tekniikasta treeniin. Lemmikeistä verotukseen.</p><a href="#gurut" aria-label="Katso Guru-palvelut"><Icon name="arrow"/></a></div></div>
 <section id="gurut" className="section container"><div className="section-heading"><div><span className="eyebrow">OMA AIHE, OMA GURU</span><h2>Kaikkea ei tarvitse<br/>tietää itse.</h2></div><p>Valitse aihe, joka mietityttää.<br/>Tutustu palveluun sen omalla sivustolla.</p></div><div className="guru-grid">{gurus.map((g,i)=><a href={g.url} key={g.name} className={`guru-card guru-${i}`}><div className="card-top"><span className="guru-icon"><Icon name={g.icon}/></span><span className="card-topic">{g.topic}</span><Icon name="external" className="card-arrow"/></div><h3>{g.question}</h3><p>{g.description}</p><span className="card-example">“{g.example}”</span><span className="card-bottom">Tutustu: {g.name}<Icon name="arrow"/></span></a>)}</div><p className="section-note">Guru-palveluiden sisällöt, palvelutavat ja hinnat löytyvät niiden omilta sivuilta.</p></section>
 <section id="miten-toimii" className="how-section"><div className="container how-grid"><div><span className="eyebrow">HELPOMPI SANOA ÄÄNEEN</span><h2>Sinä puhut.<br/>Tekoäly kuuntelee.</h2><p className="section-lead">Älypuhelimen käyttö alkaa yhdestä puhelusta. Kysy omin sanoin, vaikka et vielä tietäisi kaikkia oikeita termejä.</p><div className="sample-bubble">“Mistä tässä kannattaisi<br/>lähteä liikkeelle?”<Icon name="sound"/></div></div><ol className="steps"><li><span>01</span><div><h3>Soita Älypuhelimeen</h3><p>Numero on <a href={site.tel}>{site.phone}</a>. Ei ladattavaa sovellusta tai uutta käyttäjätiliä.</p><small>{site.price}</small></div></li><li><span>02</span><div><h3>Kerro, mistä haluat puhua</h3><p>Seuraa Guru-valinnan ohjeita ja kerro aiheesi. Puhu niin kuin puhuisit ihmiselle.</p></div></li><li><span>03</span><div><h3>Kysy lisää, jos jokin jäi auki</h3><p>Voit pyytää esimerkin tai selityksen yksinkertaisemmin. Lopetat puhelun silloin, kun sinulle sopii.</p></div></li></ol></div></section>
 <section id="hinta" className="section container pricing-grid"><div><span className="eyebrow">ÄLYPUHELIMEN HINNOITTELU</span><h2>Yksi puhelu.<br/>Ei tilausta.</h2><p className="section-lead">Haluatko pohtia ideaasi tai kysyä jotain ihan muuta? Älypuhelimen kanssa voit keskustella myös ilman tiettyä aihetta.</p><div className="price-example"><span>Esimerkiksi 5 minuuttia</span><strong>4,90 €</strong><small>+ operaattorisi pvm/mpm</small></div></div><div className="price-card"><span className="eyebrow">SOITA TEKOÄLYLLE</span><div className="price">0,98 €<span>/ min</span></div><p>+ paikallisverkko- tai matkapuhelinmaksu</p><ul><li><Icon name="check"/>Ei kuukausimaksuja</li><li><Icon name="check"/>Ei jatkuvaa tilausta</li><li><Icon name="check"/>Käytettävissä ympäri vuorokauden</li></ul><a href={site.tel} className="button button-full"><Icon name="phone"/>Soita {site.phone}<Icon name="arrow"/></a><p className="fine-print">Palvelumaksun yläraja on 50 € / puhelu. Puhelu katkaistaan rajan täyttyessä. Operaattorin maksut veloitetaan lisäksi.</p></div></section>
 <section id="ukk" className="faq-section section"><div className="container faq-grid"><div><span className="eyebrow">VIELÄKÖ MIETITYTTÄÄ?</span><h2>Hyviä kysymyksiä.</h2><p>Tässä vastaukset yleisimpiin.<br/>Loput voit kysyä meiltä.</p><a href="mailto:visa.valkonen@kaupallinen.fi" className="text-link">Ota yhteyttä<Icon name="external"/></a></div><FAQ items={faq}/></div></section>
 <section className="closing"><div className="container closing-inner"><div><span className="eyebrow">MIKÄ SINUA MIETITYTTÄÄ?</span><h2>Kysy ääneen.</h2></div><a href="#gurut" className="button">Löydä sopiva Guru<Icon name="arrow"/></a><svg className="closing-echo" viewBox="0 0 200 200" fill="none" stroke="currentColor" strokeWidth="10" aria-hidden="true"><path d="M40 65a45 45 0 0 1 0 70M75 35a85 85 0 0 1 0 130M110 5a125 125 0 0 1 0 190"/></svg></div></section>
 </main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'WebSite',name:site.name,url:site.url,publisher:{'@type':'Organization',name:'Valkomedia Oy',url:site.url}})}}/></>}
