import type {Metadata} from 'next';
import Link from 'next/link';
import Brand from '@/components/Brand';
import FAQ from '@/components/FAQ';
import Icon from '@/components/Icon';
import FloatingCTA from '@/components/FloatingCTA';
import {site} from '@/lib/site';
const title='Vittuilupuhelin – Kaikki muut kehuvat. Tämä puhelin ei.';
const description='Tekoälyn kuittailua aikuisille. Soita 0600 411 104 ja pyydä Guru-valinnassa Vittuilupuhelinta. 0,98 €/min + pvm/mpm.';
export const metadata:Metadata={title,description,alternates:{canonical:'/vittuilupuhelin'},openGraph:{title,description,url:'/vittuilupuhelin',images:[{url:'/brand/vittuilupuhelin-social.png',width:1200,height:630,alt:'Vittuilupuhelin – Kaikki muut kehuvat. Tämä puhelin ei.'}]},twitter:{card:'summary_large_image',title,description}};
const faq=[{question:'Miten löydän Vittuilupuhelimen?',answer:'Soita Älypuhelimen numeroon 0600 411 104 ja pyydä Guru-valinnassa Vittuilupuhelinta. Erillistä numeroa, sovellusta tai käyttäjätiliä ei tarvita.'},{question:'Mitä puhelu maksaa?',answer:'Palvelumaksu on 0,98 €/min + paikallisverkko- tai matkapuhelinmaksu. Esimerkiksi viiden minuutin palvelumaksu on 4,90 €. Ei kuukausimaksua tai jatkuvaa tilausta. Palvelumaksun yläraja on 50 €/puhelu, ja puhelu katkaistaan rajan täyttyessä. Operaattorin maksut tulevat lisäksi.'},{question:'Vastaako puhelimeen ihminen?',answer:'Ei. Keskustelet tekoälyn kanssa. Vittuilupuhelin on viihdepalvelu, jonka vastauksia ei pidä ottaa neuvoina tai arvioina sinusta.'},{question:'Kenelle palvelu sopii?',answer:'Aikuisille, joita karkea kieli ja itseensä kohdistuva kuittailu huvittavat. Jos kaipaat asiallista neuvontaa, tutustu Älypuhelimen Guru-palveluihin.'},{question:'Voinko lopettaa milloin tahansa?',answer:'Kyllä. Voit sulkea puhelun milloin tahansa. Palveluun ei liity jatkuvaa tilausta.'}];
export default function Page(){return <div className="roast-page"><header className="roast-header container"><Brand/><Link href="/" className="roast-back">Älypuhelimen etusivulle<Icon name="arrow"/></Link></header><main id="main"><section className="roast-hero container"><div><span className="eyebrow"><span className="status-dot"/>AI-VIIHDETTÄ AIKUISILLE</span><h1>Kaikki muut<br/>kehuvat.<br/><span>Tämä puhelin ei.</span></h1><p className="roast-lead">Vittuilupuhelimessa tekoäly kuittailee takaisin. Sinulle, joka osaat nauraa myös itsellesi.</p><a href={site.tel} className="button"><Icon name="phone"/>Soita {site.phone}<Icon name="arrow"/></a><p className="roast-price">{site.price}</p><p className="roast-instruction">Pyydä Guru-valinnassa <strong>Vittuilupuhelinta.</strong></p></div><div className="roast-visual" aria-hidden="true"><span className="roast-asterisk">*</span><div className="roast-quote">Egoa ei<br/>tarvitse<br/>ottaa mukaan.<span>VITTUILUPUHELIN</span></div><span className="roast-small-label">Ei kehuja pyytämällä.</span></div></section>
 <section className="roast-how container section"><div className="section-heading"><div><span className="eyebrow">NÄIN PÄÄSET LINJOILLE</span><h2>Ei sen vaikeampaa.</h2></div></div><ol className="roast-steps"><li><span>01</span><h3>Soita samaan numeroon.</h3><p>Älypuhelin vastaa numerossa {site.phone}. {site.price}.</p></li><li><span>02</span><h3>Pyydä Vittuilupuhelinta.</h3><p>Kerro Guru-valinnassa, että haluat Vittuilupuhelimen.</p></li><li><span>03</span><h3>Anna tulla takaisin.</h3><p>Juttele tekoälyn kanssa. Kun riittää, sulje puhelu.</p></li></ol></section>
 <section className="roast-example"><div className="container"><span className="eyebrow">MAISTIAINEN SÄVYSTÄ</span><blockquote>“Sun tehtävälista on enemmän historiallinen dokumentti kuin suunnitelma.”</blockquote><p>Kirjoitettu esimerkki huumorin tyylistä, ei tallenne asiakaspuhelusta.</p></div></section>
 <section className="section container faq-grid"><div><span className="eyebrow">IHAN ASIALLISET VASTAUKSET</span><h2>Ennen kuin soitat.</h2><p>Vittuilupuhelin on viihdettä.<br/>Sinä päätät, milloin riittää.</p></div><FAQ items={faq}/></section>
 <section className="roast-final container"><h2>No, uskallatko?</h2><a className="button" href={site.tel}><Icon name="phone"/>Soita {site.phone}</a><p>{site.price} · Pyydä Guru-valinnassa Vittuilupuhelinta.</p><Link href="/">Kuittailun sijaan apua? Tutustu Guruihin →</Link></section></main><footer className="roast-footer container"><Brand/><p>Valkomedia Oy · Y-tunnus 2360847-3</p><Link href="/tietosuoja">Tietosuojaseloste</Link><a href="mailto:visa.valkonen@kaupallinen.fi">Ota yhteyttä</a></footer><FloatingCTA/></div>}
